"""
`makemigrations` reporting.

Alembic autogenerate always writes a revision file, even when it found no
schema drift, so an unchanged project quietly accumulated revisions whose
upgrade() was `pass` -- indistinguishable in the history from real ones.
"""

from buraq.management.cli import _is_empty_migration

HEADER = [
    '"""a revision"""',
    "from alembic import op",
    "import sqlalchemy as sa",
    "",
    'revision = "abc123"',
    "down_revision = None",
    "",
    "",
]

FOOTER = ["", "", "def downgrade() -> None:", "    pass", ""]


def _revision(tmp_path, name, upgrade_lines):
    """Write a revision file whose upgrade() body is `upgrade_lines`."""
    body = [f"    {line}" if line else "" for line in upgrade_lines]
    source = HEADER + ["def upgrade() -> None:"] + body + FOOTER
    path = tmp_path / f"{name}.py"
    path.write_text("\n".join(source), encoding="utf-8")
    compile(path.read_text(encoding="utf-8"), str(path), "exec")  # guard the fixture
    return path


def test_a_revision_that_does_nothing_is_recognised(tmp_path):
    path = _revision(tmp_path, "empty", ["pass"])

    assert _is_empty_migration(path) is True


def test_comments_alone_do_not_make_a_revision_meaningful(tmp_path):
    """Autogenerate brackets its output in comments even when it emitted none."""
    path = _revision(
        tmp_path,
        "commented",
        [
            "# ### commands auto generated by Alembic - please adjust! ###",
            "pass",
            "# ### end Alembic commands ###",
        ],
    )

    assert _is_empty_migration(path) is True


def test_a_docstring_does_not_count_as_an_operation(tmp_path):
    path = _revision(tmp_path, "docstring", ['"""Upgrade schema."""', "pass"])

    assert _is_empty_migration(path) is True


def test_a_revision_with_a_real_operation_is_kept(tmp_path):
    path = _revision(
        tmp_path,
        "real",
        ["op.add_column('posts', sa.Column('subtitle', sa.String(), nullable=True))"],
    )

    assert _is_empty_migration(path) is False


def test_a_batch_operation_is_kept(tmp_path):
    """SQLite drift arrives wrapped in batch_alter_table, not a bare op call."""
    path = _revision(
        tmp_path,
        "batch",
        [
            "with op.batch_alter_table('posts', schema=None) as batch_op:",
            "    batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))",
        ],
    )

    assert _is_empty_migration(path) is False


def test_an_unparsable_file_is_left_alone(tmp_path):
    """Never delete something we could not read -- it may be hand-edited."""
    path = tmp_path / "broken.py"
    path.write_text("def upgrade(: pass", encoding="utf-8")

    assert _is_empty_migration(path) is False


def test_a_missing_file_is_not_treated_as_empty(tmp_path):
    assert _is_empty_migration(tmp_path / "gone.py") is False


def test_a_file_without_an_upgrade_function_is_left_alone(tmp_path):
    path = tmp_path / "notarevision.py"
    path.write_text("x = 1\n", encoding="utf-8")

    assert _is_empty_migration(path) is False


# ─── The positional argument ──────────────────────────────────────────────────

def test_an_app_name_is_recognised_as_a_likely_mistake(monkeypatch):
    """
    Django's positional argument is an app label, so `makemigrations posts` is a
    natural thing to type -- and it would silently become the description of a
    migration covering every model in the project.
    """
    from buraq.conf import settings
    from buraq.management.cli import _names_an_installed_app

    monkeypatch.setattr(
        settings, "INSTALLED_APPS", ["posts", "buraq.contrib.auth", "blog.apps.BlogConfig"]
    )

    assert _names_an_installed_app("posts")
    assert _names_an_installed_app("auth")            # trailing label
    assert _names_an_installed_app("blog")            # leading package
    assert _names_an_installed_app("buraq.contrib.auth")


def test_a_real_description_is_left_alone(monkeypatch):
    from buraq.conf import settings
    from buraq.management.cli import _names_an_installed_app

    monkeypatch.setattr(settings, "INSTALLED_APPS", ["posts"])

    assert not _names_an_installed_app("add slug to post")
    assert not _names_an_installed_app("initial")
